<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

// list of common timezones in order
$config['common_timezones'] = array(  

// ------------------------------------------- 
'(GMT-11:00) Samoa' => 'Pacific/Apia',
'(GMT-10:00) Hawaii' => 'Pacific/Honolulu',
'(GMT-09:00) Alaska' => 'America/Anchorage',
'(GMT-08:00) Pacific Time' => 'America/Los_Angeles',
'(GMT-07:00) Arizona' => 'America/Phoenix',
'(GMT-07:00) Mazatlan' => 'America/Chihuahua',
'(GMT-07:00) Mountain Time' => 'America/Denver',
'(GMT-06:00) Central America' => 'America/Managua',
'(GMT-06:00) Central Time' => 'America/Chicago',
'(GMT-06:00) Monterrey' => 'America/Mexico_City',
'(GMT-06:00) Saskatchewan' => 'America/Regina',
'(GMT-05:00) Quito' => 'America/Bogota',
'(GMT-05:00) Eastern Time' => 'America/New_York',
'(GMT-05:00) Indiana (East)' => 'America/Indiana/Indianapolis',
'(GMT-04:00) Atlantic Time' => 'America/Halifax',
'(GMT-04:00) La Paz' => 'America/Caracas',
'(GMT-04:00) Santiago' => 'America/Santiago',
'(GMT-03:30) Newfoundland' => 'America/St_Johns',
'(GMT-03:00) Brasilia' => 'America/Sao_Paulo',
'(GMT-03:00) Georgetown' => 'America/Argentina/Buenos_Aires',
'(GMT-03:00) Greenland' => 'America/Godthab',
'(GMT-02:00) Mid-Atlantic' => 'America/Noronha',
'(GMT-01:00) Azores' => 'Atlantic/Azores',
'(GMT-01:00) Cape Verde Is.' => 'Atlantic/Cape_Verde',
'(GMT+00:00) Monrovia' => 'Africa/Casablanca',
'(GMT+00:00) London' => 'Europe/London',
'(GMT+01:00) Vienna' => 'Europe/Berlin',
'(GMT+01:00) Prague' => 'Europe/Belgrade',
'(GMT+01:00) Paris' => 'Europe/Paris',
'(GMT+01:00) Zagreb' => 'Europe/Sarajevo',
'(GMT+01:00) West Central Africa' => 'Africa/Lagos',
'(GMT+02:00) Minsk' => 'Europe/Istanbul',
'(GMT+02:00) Bucharest' => 'Europe/Bucharest',
'(GMT+02:00) Cairo' => 'Africa/Cairo',
'(GMT+02:00) Pretoria' => 'Africa/Johannesburg',
'(GMT+02:00) Vilnius' => 'Europe/Helsinki',
'(GMT+02:00) Jerusalem' => 'Asia/Jerusalem',
'(GMT+03:00) Baghdad' => 'Asia/Baghdad',
'(GMT+03:00) Riyadh' => 'Asia/Riyadh',
'(GMT+03:00) Volgograd' => 'Europe/Moscow',
'(GMT+03:00) Nairobi' => 'Africa/Nairobi',
'(GMT+03:30) Tehran' => 'Asia/Tehran',
'(GMT+04:00) Muscat' => 'Asia/Muscat',
'(GMT+04:00) Yerevan' => 'Asia/Tbilisi',
'(GMT+04:30) Kabul' => 'Asia/Kabul',
'(GMT+05:00) Ekaterinburg' => 'Asia/Yekaterinburg',
'(GMT+05:00) Tashkent' => 'Asia/Karachi',
'(GMT+05:30) New Delhi' => 'Asia/Calcutta',
'(GMT+05:45) Kathmandu' => 'Asia/Katmandu',
'(GMT+06:00) Novosibirsk' => 'Asia/Novosibirsk',
'(GMT+06:00) Dhaka' => 'Asia/Dhaka',
'(GMT+06:00) Sri Jayawardenepura' => 'Asia/Colombo',
'(GMT+06:30) Rangoon' => 'Asia/Rangoon',
'(GMT+07:00) Jakarta' => 'Asia/Bangkok',
'(GMT+07:00) Krasnoyarsk' => 'Asia/Krasnoyarsk',
'(GMT+08:00) Urumqi' => 'Asia/Hong_Kong',
'(GMT+08:00) Ulaan Bataar' => 'Asia/Irkutsk',
'(GMT+08:00) Singapore' => 'Asia/Singapore',
'(GMT+08:00) Perth' => 'Australia/Perth',
'(GMT+08:00) Taipei' => 'Asia/Taipei',
'(GMT+09:00) Tokyo' => 'Asia/Tokyo',
'(GMT+09:00) Seoul' => 'Asia/Seoul',
'(GMT+09:00) Yakutsk' => 'Asia/Yakutsk',
'(GMT+09:30) Adelaide' => 'Australia/Adelaide',
'(GMT+09:30) Darwin' => 'Australia/Darwin',
'(GMT+10:00) Brisbane' => 'Australia/Brisbane',
'(GMT+10:00) Sydney' => 'Australia/Sydney',
'(GMT+10:00) Port Moresby' => 'Pacific/Guam',
'(GMT+10:00) Hobart' => 'Australia/Hobart',
'(GMT+10:00) Vladivostok' => 'Asia/Vladivostok',
'(GMT+11:00) Solomon Is.' => 'Asia/Magadan',
'(GMT+12:00) Wellington' => 'Pacific/Auckland',
'(GMT+12:00) Marshall Is.' => 'Pacific/Fiji',
// -------------------------------------------

);

?>